- hosts: webservers
  gather_facts: "{{ do_gather_facts | default(true) }}"

  tasks:
    - name: install git server
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
