- hosts: webservers
  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html
  become: yes
  
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
        mode: '0644'

    - name: Copy nginx.conf
      ansible.builtin.template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
